### ISSUE TITLE
Error upon launch

### ISSUE THREAD

**Issue by rthfhgyhy567** [FoxAhead/Far-Cry-2-Multi-Fixer#10]
I get this error on the steam version whenever I have sweet fx installed.  It runs fine without it, however I can't tolerate this game without both :(

https://imgur.com/a/Ainfq9L

**Comment by FoxAhead** [comment]
This problem has nothing to do with Multi-Fixer.
Try searching the Internet for information on this error.

**Comment by rthfhgyhy567** [comment]
> This problem has nothing to do with Multi-Fixer. Try searching the Internet for information on this error.

RUDE!!

If this issue had nothing to do with your tool, then why does it only occur when running it?  Launching the vanilla Far Cry 2.exe works fine.  Maybe you should do some research before quickly arriving to such a conclusion.  Unlike you, I actually DID do research, and have determined this is YOUR problem.  So I will be uninstalling your dud software.  Thanks for wasting my time.

**Comment by FoxAhead** [comment]
I searched for you:
https://steamcommunity.com/app/2600/discussions/0/133262487498362725/?ctp=3
https://steamcommunity.com/sharedfiles/filedetails/?id=1791690985
The problem caused by SweetFX. The solution is to either rename or delete both files dxgi.dll and dxgi.fx.

**Comment by FoxAhead** [comment]
> > This problem has nothing to do with Multi-Fixer. Try searching the Internet for information on this error.
> 
> RUDE!!
> 
> If this issue had nothing to do with your tool, then why does it only occur when running it? Launching the vanilla Far Cry 2.exe works fine. Maybe you should do some research before quickly arriving to such a conclusion. Unlike you, I actually DID do research, and have determined this is YOUR problem. So I will be uninstalling your dud software. Thanks for wasting my time.

https://www.reddit.com/r/techsupport/comments/90l867/cant_open_the_game_far_cry_2_over_something_in/



>Try this:
>    Go to your games folder (usually Program Files (x86)/steam/steamapps/common/Far Cry 2) - or wherever your game folder is stored.
>    Locate dxgi.dll. (If it's not there, go to (C:)/windows/system32 and copy+paste it from there.)
>    Rename dxgi.dll to d3d11.dll in your game folder

And

>So the real problem here is that the system environment PATH variable got messed up, or Far Cry didn't read from it. SweetFX >probably changed the graphics API library for it's own modifications, overriding the system version, and when you removed >SweetFX/ReShade, the link library was looking for the modded files and it couldn't find them. Reinstalling the D3D runtime fixed >this problem, but it wasn't the only solution.

**Comment by rthfhgyhy567** [comment]
https://imgur.com/VMlajGB

I also tried download all the [runtimes](https://directx-11.en.lo4d.com/windows) and copying and pasting the d3d11.dll from the system 32 folder into the game's bin folder.  I guess it is what it is.  Just gonna uninstall this shit game along with your shit software and play newer games I guess.

**Comment by BigTinz** [comment]
This just sounds like a user error by a rude moron. 

FoxAhead has done an amazing job, and is vital to the FC2 mod community. 

This tool has worked for thousands of players. Maybe your PC sucks, or you just don't know what you're doing. 

Sounds like you're not mature enough for this game, anyway.

**Comment by rthfhgyhy567** [comment]
> This just sounds like a user error by a rude moron.
> 
> FoxAhead has done an amazing job, and is vital to the FC2 mod community.
> 
> This tool has worked for thousands of players. Maybe your PC sucks, or you just don't know what you're doing.
> 
> Sounds like you're not mature enough for this game, anyway.

I've been playing this game off and on since 2009. The tool is clearly a dud, and even the author doesn't even know what's wrong.  I have enough evidence to back up this claim.  And by the way, what does the quality of my PC have to do with a software error that the developer is so keen on covering up by closing my thread and playing the blame game?  The user should not have to have the same level of knowledge as the developer to install a mode (in this case it wouldn't even matter since the dev doesn't even know where the problem lies or how to solve it, and would rather shift the blame to the user).

Anyways I'm unsubbing from this thread since both of you make broken software for crap 15 year old games and are over confident pricks that think you know more than everyone.

Good day jackass.

**Comment by rthfhgyhy567** [comment]
I found out that this error only happens for me the farcry2.exe is directly launched (in this case because of your tool) without steam.  I never did figure out why, but launching the Multi fixer through steam as a non-steam game lets me launch the game without any errors.  Either way, these errors are just annoying warnings and do not affect functionality.
