### ISSUE TITLE
Game Wont Launch

### ISSUE THREAD

**Issue by SachsA** [FoxAhead/Far-Cry-2-Multi-Fixer#12]
Hello
I Downloaded the zip, unzip it in my Download folder. Both dll and .exe are located in my download folder like you said.
But when I click on play, the image of far cry 2 breifely pop then it disappears and there is not process in the background.
What should I do ?

<img width="548" alt="Capture" src="https://github.com/FoxAhead/Far-Cry-2-Multi-Fixer/assets/27199365/c3ccfcab-d92d-4e3d-8a0e-0cf850e524fa">

<img width="396" alt="Capture1" src="https://github.com/FoxAhead/Far-Cry-2-Multi-Fixer/assets/27199365/81e6f44b-dc1d-4255-bad6-4997f78454ad">

<img width="604" alt="Capture2" src="https://github.com/FoxAhead/Far-Cry-2-Multi-Fixer/assets/27199365/25b0af3b-ec4d-4155-b1e8-83844395555a">

**Comment by FoxAhead** [comment]
Is your game modded?
Are you using ReShade?
Does this happens without multifixer?
Try DX9 instead of DX10.
Try set CPU affinity in options.
Try compatibility mode.
Take a look at this threads:
https://steamcommunity.com/app/19900/discussions/0/3811783264381648259/
https://steamcommunity.com/app/19900/discussions/0/3805029641872539448/
https://steamcommunity.com/app/19900/discussions/0/3805029995446915593/

**Comment by SachsA** [comment]
You answer so fast ! Thank you so much.
- game not modded
- No reshade
- It happens with AND without multifixer
- It’s runned with DX9
- I’ll try compatibility and CPU affinity options, i’ll try tomorrow i’ll give you some news

the only way i manage to launch the game is with this method:
https://steamcommunity.com/app/19900/discussions/0/6382186451019614276/

But I cannot do it with multifixer

I’ll try what you suggest tomorrow

**Comment by FoxAhead** [comment]
The link you provided is just about CPU affinity.  If this method really helped you, then instead of using a shortcut, you can use the option "Processor affinity" in the MultiFixer itself. Click "Options...", enable "Processor affinity", set the value of "Affinity mask" to "1".

**Comment by SachsA** [comment]
Ok I'll try it this evening when I come back. I'll let you know instantly.

**Comment by SachsA** [comment]
Hi @FoxAhead just to inform you that CPU affinity was the tricks for me. Sorry for opening an issue I was desperate, have a nice day.
