### ISSUE TITLE
DLL not loaded ERROR

### ISSUE THREAD

**Issue by LongJohnson1991** [FoxAhead/Far-Cry-2-Multi-Fixer#13]
DLL Error Game keeps crashing on fullscreen! 
![Screenshot 2024-04-11 021911](https://github.com/FoxAhead/Far-Cry-2-Multi-Fixer/assets/29235374/d1fb4f54-9dc4-448b-b87d-f48d54c4923a)

**Comment by BigTinz** [comment]
1. Relocate the Far Cry 2 folder to a lower level on your main drive. Something like C:\Far Cry 2

2. Extract/move the Multi-Fixer files to the bin folder

That should work.

**Comment by LongJohnson1991** [comment]
> 1. Relocate the Far Cry 2 folder to a lower level on your main drive. Something like C:\Far Cry 2
> 2. Extract/move the Multi-Fixer files to the bin folder
> 
> That should work.

Worked thank you and the Graphic mod was faulty i used works perfectly now ^^
