### ISSUE TITLE
Additional option for command line argument to allow direct launch (GOG)

### ISSUE THREAD

**Issue by JoseWhite** [FoxAhead/Far-Cry-2-Multi-Fixer#3]
Create or include in readme a way of launching the game through GOG without opening the configuration tool.
(Even if "shortcut" is created using the "create a shortcut" button when GOG uses that shortcut it just launches the configuration tool instead of the game directly)

**Comment by FoxAhead** [comment]
"launching the game through GOG" -  do you mean GOG Galaxy?

**Comment by FoxAhead** [comment]
I don't have any experience with GOG Galaxy launcher, but may be this guide could be helpful
https://steamcommunity.com/sharedfiles/filedetails/?id=1620638035
Look at section "Steam Overlay and playtime (alternative method)". Note - there is `-play` option
May be something similar could be done in GOG Galaxy.

**Comment by JoseWhite** [comment]
> "launching the game through GOG" - do you mean GOG Galaxy?
Yes, GoG Galaxy 2.0

**Comment by JoseWhite** [comment]
> I don't have any experience with GOG Galaxy launcher, but may be this guide could be helpful
> https://steamcommunity.com/sharedfiles/filedetails/?id=1620638035
> Look at section "Steam Overlay and playtime (alternative method)". Note - there is `-play` option.
> May be something similar could be done in GOG Galaxy.

I've had no luck searching for a equivalent flag on Galaxy 2.0. It's quite likely that the flag exists but like many platforms there's little documentation about it

Update, Since the time of writing the initial issue,
I have changed the regular farcry2.exe as the default game launcher to the multi-fixer shortcut and even though Its necessary to press play every time on the tool like I said It does count the game session time so, this request/issue is no longer as important.

For anyone wondering how to; as of GoG Galaxy 2.0, just press configure on the specific game, add a executable, set its path to the Multifixer tool and set that executable as the default. Maybe you could add this to the readme if you think its useful enough :smile: .

Thanks for the fast reply and sorry for the not so quick response :woozy_face:
