### ISSUE TITLE
Potential to pirate the game.

### ISSUE THREAD

**Issue by Theguild123** [FoxAhead/Far-Cry-2-Multi-Fixer#6]
I used this to change the fov and then decided i didnt like the game, ive refunded it but the game files is still downloaded. I was curious so i started up the multi fixer and launched through there. This let me play the game despite it being unavailable to my steam account.

**Comment by FoxAhead** [comment]
MultiFixer has nothing to do with this.
It's a Steam issue that it didn't delete the game files after refunding. So you can play this game even without MultiFixer. Just open File Explorer and navigate to the game folder. Find the farcry.exe file and run it. Following your logic, you can blame Microsoft Windows of allowing you to play this game and of piracy. And who knows, maybe you yourself copied the game files before returning the money?

**Comment by Theguild123** [comment]
No steam doesnt let you play it when its imstalled and you cant use the fules inside to launch it when its refunded. But launchin it in the program you can.

**Comment by BigTinz** [comment]
You're mistaken, Guild. FC2 is DRM free on steam. You could download, move the files, then refund and the game would still work. This has nothing to do with Fox's program.
