### ISSUE TITLE
Possibility to add a fix for the Infamous healing issue to the launcher? 

### ISSUE THREAD

**Issue by ProxyNode1** [FoxAhead/Far-Cry-2-Multi-Fixer#9]
Hi! I was wondering is it possible to add the fix for the infamous healing issue to the launcher. Since the only mod that fixes this, the hunter's mod, comes with other modified stuff as well and I want to keep the game as vanilla as possible. Thanks.

**Comment by BigTinz** [comment]
No. That bug is in the game files, not the .dll.

Check out Boggalog's modding guide (steam, modDB, etc.) and it will explain how to make this modification yourself, with your own files.
